/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 07180a97aef8b4054fbd09cd86b90bfe27cb19a3e9c19ef2120aa0de5d5bb63d.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `redux` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::warp::convert_redux;
use dialect_nvvm::ops::{
    ReduxSyncAddOp, ReduxSyncAndOp, ReduxSyncFmaxAbsNanOp, ReduxSyncFmaxAbsOp, ReduxSyncFmaxNanOp,
    ReduxSyncFmaxOp, ReduxSyncFminAbsNanOp, ReduxSyncFminAbsOp, ReduxSyncFminNanOp,
    ReduxSyncFminOp, ReduxSyncMaxOp, ReduxSyncMinOp, ReduxSyncOrOp, ReduxSyncUmaxOp,
    ReduxSyncUminOp, ReduxSyncXorOp,
};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncAddOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_add",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncAndOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_and",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncFmaxAbsOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_fmax_abs",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncFmaxAbsNanOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_fmax_abs_NaN",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncFmaxOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_fmax",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncMaxOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_max",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncFmaxNanOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_fmax_NaN",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncUmaxOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_umax",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncFminAbsOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_fmin_abs",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncFminAbsNanOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_fmin_abs_NaN",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncFminOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_fmin",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncMinOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_min",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncFminNanOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_fmin_NaN",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncUminOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_umin",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncOrOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_or",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncXorOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_xor",
        )
    }
}
