; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 07180a97aef8b4054fbd09cd86b90bfe27cb19a3e9c19ef2120aa0de5d5bb63d.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.barrier.cta.sync.count(i32, i32)

define void @probe_barrier_cta_sync_rr(i32 %barrier_id, i32 %thread_count) #0 {
  call void @llvm.nvvm.barrier.cta.sync.count(i32 %barrier_id, i32 %thread_count)
  ret void
}

define void @probe_barrier_cta_sync_ri(i32 %barrier_id) #0 {
  call void @llvm.nvvm.barrier.cta.sync.count(i32 %barrier_id, i32 32)
  ret void
}

define void @probe_barrier_cta_sync_ir(i32 %thread_count) #0 {
  call void @llvm.nvvm.barrier.cta.sync.count(i32 1, i32 %thread_count)
  ret void
}

define void @probe_barrier_cta_sync_ii() #0 {
  call void @llvm.nvvm.barrier.cta.sync.count(i32 1, i32 32)
  ret void
}

attributes #0 = { convergent }
