; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 3df52944985ca17502f6d46dac02c640ef6a6abb7784a1f72fb0dced7c24e3ad.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.barrier.cta.arrive.aligned.count(i32, i32)

define void @probe_barrier_cta_arrive_aligned_rr(i32 %barrier_id, i32 %thread_count) #0 {
  call void @llvm.nvvm.barrier.cta.arrive.aligned.count(i32 %barrier_id, i32 %thread_count)
  ret void
}

define void @probe_barrier_cta_arrive_aligned_ri(i32 %barrier_id) #0 {
  call void @llvm.nvvm.barrier.cta.arrive.aligned.count(i32 %barrier_id, i32 32)
  ret void
}

define void @probe_barrier_cta_arrive_aligned_ir(i32 %thread_count) #0 {
  call void @llvm.nvvm.barrier.cta.arrive.aligned.count(i32 1, i32 %thread_count)
  ret void
}

define void @probe_barrier_cta_arrive_aligned_ii() #0 {
  call void @llvm.nvvm.barrier.cta.arrive.aligned.count(i32 1, i32 32)
  ret void
}

attributes #0 = { convergent }
