; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 3df52944985ca17502f6d46dac02c640ef6a6abb7784a1f72fb0dced7c24e3ad.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.clusterlaunchcontrol.try_cancel.async.multicast.shared(ptr addrspace(3), ptr addrspace(3))

define void @probe_clc_try_cancel_multicast(ptr %response_generic, ptr %mbarrier_generic) {
  %response = addrspacecast ptr %response_generic to ptr addrspace(3)
  %mbarrier = addrspacecast ptr %mbarrier_generic to ptr addrspace(3)
  call void @llvm.nvvm.clusterlaunchcontrol.try_cancel.async.multicast.shared(ptr addrspace(3) %response, ptr addrspace(3) %mbarrier)
  ret void
}
