; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 07180a97aef8b4054fbd09cd86b90bfe27cb19a3e9c19ef2120aa0de5d5bb63d.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare { i32, i1 } @llvm.nvvm.elect.sync(i32) #0

define { i32, i1 } @probe_elect_sync_llvm_nvptx_register(i32 %mask) #0 {
  %result = call { i32, i1 } @llvm.nvvm.elect.sync(i32 %mask) #0
  ret { i32, i1 } %result
}
define { i32, i1 } @probe_elect_sync_llvm_nvptx_immediate() #0 {
  %result = call { i32, i1 } @llvm.nvvm.elect.sync(i32 -1) #0
  ret { i32, i1 } %result
}

attributes #0 = { convergent }
