; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 07180a97aef8b4054fbd09cd86b90bfe27cb19a3e9c19ef2120aa0de5d5bb63d.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i64 @probe_fma_ftz_f32x2(i64 %arg0, i64 %arg1, i64 %arg2) {
  %result = call i64 asm "fma.rn.ftz.f32x2 $0, $1, $2, $3;", "=l,l,l,l"(i64 %arg0, i64 %arg1, i64 %arg2)
  ret i64 %result
}
