; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 3df52944985ca17502f6d46dac02c640ef6a6abb7784a1f72fb0dced7c24e3ad.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i16 @probe_min_nan_xorsign_abs_bf16(i16 %a, i16 %b) {
  %result = call i16 asm "min.NaN.xorsign.abs.bf16 $0, $1, $2;", "=h,h,h"(i16 %a, i16 %b)
  ret i16 %result
}
