; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 07180a97aef8b4054fbd09cd86b90bfe27cb19a3e9c19ef2120aa0de5d5bb63d.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i16 @probe_min_ftz_nan_xorsign_abs_f16(i16 %a, i16 %b) {
  %result = call i16 asm "min.ftz.NaN.xorsign.abs.f16 $0, $1, $2;", "=h,h,h"(i16 %a, i16 %b)
  ret i16 %result
}
