; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 3df52944985ca17502f6d46dac02c640ef6a6abb7784a1f72fb0dced7c24e3ad.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define { i32, i32 } @probe_mma_m16n8k32_f16_e3m2_e2m1(i32 %c0, i32 %c1, i32 %a0, i32 %a1, i32 %a2, i32 %a3, i32 %b0, i32 %b1) #0 {
  %result = call { i32, i32 } asm sideeffect "mma.sync.aligned.m16n8k32.row.col.kind::f8f6f4.f16.e3m2.e2m1.f16 {$0, $1}, {$4, $5, $6, $7}, {$8, $9}, {$2, $3};", "=r,=r,r,r,r,r,r,r,r,r"(i32 %c0, i32 %c1, i32 %a0, i32 %a1, i32 %a2, i32 %a3, i32 %b0, i32 %b1) #0
  ret { i32, i32 } %result
}

attributes #0 = { convergent }
