; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 3df52944985ca17502f6d46dac02c640ef6a6abb7784a1f72fb0dced7c24e3ad.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_neg_bf16x2(i32 %arg0) {
  %result = call i32 asm "neg.bf16x2 $0, $1;", "=r,r"(i32 %arg0)
  ret i32 %result
}
