; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 3df52944985ca17502f6d46dac02c640ef6a6abb7784a1f72fb0dced7c24e3ad.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.ld.16x128b.x1; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_ld_16x128b_x1_pack16(i32 %tmem) #0 {
  %result = call { i32, i32 } asm sideeffect "tcgen05.ld.sync.aligned.16x128b.x1.pack::16b.b32 {$0,$1}, [$2];", "=r,=r,r,~{memory}"(i32 %tmem) #0
  ret void
}

attributes #0 = { convergent }
