; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 07180a97aef8b4054fbd09cd86b90bfe27cb19a3e9c19ef2120aa0de5d5bb63d.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.cp.64x128b_warpx2_01_23.cg1; route: inline PTX; source contract: ExactTablegenSelection
define void @probe_tcgen05_cp_64x128b_warpx2_01_23(i32 %tmem, i64 %desc) #0 {
  call void asm sideeffect "tcgen05.cp.cta_group::1.64x128b.warpx2::01_23 [$0], $1;", "r,l,~{memory}"(i32 %tmem, i64 %desc) #0
  ret void
}

attributes #0 = { convergent }
