; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 3df52944985ca17502f6d46dac02c640ef6a6abb7784a1f72fb0dced7c24e3ad.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define void @probe_tensormap_replace_box_dim(ptr %tensor_map, i32 %new_value) {
  call void asm sideeffect "tensormap.replace.tile.box_dim.global.b1024.b32 [$0], $1, $2;", "l,n,r,~{memory}"(ptr %tensor_map, i32 0, i32 %new_value)
  ret void
}
